CREATE TABLE IF NOT EXISTS chops (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  inn TEXT NOT NULL UNIQUE,
  name TEXT,
  website TEXT,
  description TEXT,
  address TEXT,
  phone TEXT,
  email TEXT,
  license_number TEXT,
  logo_url TEXT,
  status TEXT DEFAULT 'verified',
  rating DECIMAL(3,2) DEFAULT 0,
  reviews_count INTEGER DEFAULT 0,
  employees_count INTEGER,
  founded_year INTEGER,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  created_by UUID
);
